# Generated by Django 3.1.7 on 2021-04-03 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=1000)),
                ('link', models.CharField(max_length=1000)),
                ('image', models.CharField(max_length=1000)),
                ('homepage', models.CharField(max_length=1000)),
                ('time', models.DateTimeField()),
            ],
            options={
                'db_table': 'article',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=1000)),
                ('title', models.CharField(max_length=1000)),
                ('link', models.CharField(max_length=1000)),
                ('end_date', models.CharField(max_length=1000)),
                ('time', models.DateTimeField()),
            ],
            options={
                'db_table': 'job',
            },
        ),
    ]
